#!/bin/bash

# Example project environment 
module add miniconda3-4.5.11-gcc-8.2.0-oqs2mbg  
module add fsl-6.0.4
module load matlab-2018b
 
# Set up project-specific python environment
source activate /home/data/abcd/code/env/abcd

# Set Python path to project-specific folder
PYTHONPATH="${PYTHONPATH}:/home/data/abcd/code/env"

export project_name="[abcd]"
